services:

  db:
    #    https://hub:docker.com/_/postgres
    image: postgres:17-alpine3.23
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  framd:
    image: romanempiredev/framd:latest
    user: "3013:3013"
    restart: unless-stopped
    ports:
      - "7878:7878"
    environment:
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    volumes:
      - ${MEDIA_PATH}:/media:ro
      - ${PREVIEW_LOCAL_PATH}:/previews
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata: